name: SNOWFLAKE_CICD

on:
  push:
    branches:
      - master
    paths:
      - 'Migrations/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install schemachange and snowflake connector
        run: |
          pip install --upgrade snowflake-connector-python schemachange

      - name: Decode private key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | base64 -d > decoded_private_key.pem

      - name: Decode private key passphrase
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}"  > decoded_private_key_passphrase.txt

      - name: Create connections.toml
        run: |
          cat <<EOF > connections.toml
          [connections.testconnection]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          private-key = "$(cat decoded_private_key.pem)"
          private_key_file_pwd = "$(cat decoded_private_key_passphrase.txt)"
          EOF
          cat connections.toml

      - name: Secure connections.toml permissions
        run: chmod 600 connections.toml

      - name: Run schemachange
        run: schemachange -f Migrations --connections-file-path connections.toml --connection-name testconnection
